travis:
  secure:
    BINSTAR_TOKEN: MpKG1hMrVmZVkfkjbbEKFoP/KPQGyK4XggesBUlpGYBs6usgOtFVQT3Sty6B/FwmrJTgMWaBIbbl9rPs8+frpwXBjlikEIaWQfz9vhtq71gy0SpQDjfPQDwmgqr6ZXb72RgCz06fjLaL7T1mraUUV4wKrroH5w20EkwEl86MeKD1MzjdpplYHh2FYvrnwGeVsGGNus4B7/7uscML+0b7nM0TN1oFxOavFkOx+YOcqfbvVgVcNUxz3IadOORFXbRHlg/2JxBLOcFRE1PfDC9dtjBlvEXx/opSZA71sGC0XvKUvMxKXIjONI4GgZjv+dm3ScCm1aYibd/ZPxJvZnMTUzb8ksSbbUCC+p1TH/QsLK1EpsFlhKda/dAMyx8D53vrsZZ3gizU+4GEtB5wg/yT/Vo/GWAvkkAyfOGQ/swR3wU91Y6PR+NETYTBwa2gzNMMbAFaocAA1NcdCVkFK2jCKLkz4C3RcpH1SB6TwhofRFbaorjiCqzO8ZAkoWSuv7G5Yrn4RJrw9ijA8rCAOwm3Sd3PF+ygjigqvyi2e0QQ5nNf6EOZMys00rSr80HYLyxK+8X0ADU/cNdd7bvYkbySWcx7kZMa2n9E2gPNpulpQhdO4TbCpIP9XLmPjdii2cf/yDjd7K0ZeAaB2/wv3W78Su1GgRmobD8/xY4e09NnCjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
